### model
model_name_or_path: inclusionAI/Ring-lite-distill
trust_remote_code: true
# flash_attn: fa2

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
deepspeed: examples/deepspeed/ds_z2_offload_config.json   # deepspeed: ds_z2_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: dpo_zh_demo
template: bailing
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Ring-lite-distill/full/dpo
report_to: tensorboard
logging_dir: saves/Ring-lite-distill/full/dpo/run
logging_steps: 1
save_steps: 50000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
pure_bf16: true

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
